[toolchain]
anchor_version = "0.27.0"

[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_social_media = "DTmB251A85c6vD7HdrmULfPnVuj7AXkRx528kdVaiR1Z"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/oozrooh/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
